# Uncomment the next line to define a global platform for your project
# platform :iOS, '9.0'

target 'TrainingBud' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrainingBud
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'MaterialComponents/Chips'
  pod 'RealmSwift'  
  pod 'AnimatedCollectionViewLayout'
  pod 'FittedSheets'
 
end
